modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/Jaffe2718/steroid_planet/issues"
license = "MIT"

[[mods]]
modId = "steroid_planet"
version = "${version}"
displayName = "Steroid Planet"
authors = "Jaffe2718"
description = '''
Steroid Planet adds a high-stakes bodybuilding system to Minecraft! Unlock tiered steroids (I/II/III) to boost muscle mass, reduce body fat, and chase extreme milestones like "Fat Loss Master" (≤10% body fat) or "Steroid Master" (use 9 types of steroid). Track critical stats—muscle, liver health, and body fat—with risky tradeoffs: steroids grant power but risk permanent liver damage. Earn challenge-tier advancements, unique rewards, and face the consequences of reckless fitness pursuit in this adrenaline-fueled progression mod.
'''
logoFile = "assets/steroid_planet/icon.png"
modUrl = "https://modrinth.com/mod/steroid_planet"

[[dependencies.steroid_planet]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.steroid_planet]]
modId = "minecraft"
type = "required"
versionRange = "${neoforge_mc_versions}"
ordering = "NONE"
side = "BOTH"

[[dependencies.steroid_planet]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_api_min},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "steroid_planet.neoforge.mixins.json"
